### PR TITLE
Lindz/credits edit

### PR DESCRIPTION
**Pull request by walkerlj0**
Added Archiving & registration, links to Starling Lab and Github, as well as .gitignore for node modules

### CODE REVIEW

**Review by makew0rld — APPROVED** [review]
Looks good, although I didn't realize we still wanted to publish to Distributed Press currently.

**Comment by fauno** [comment]
@walkerlj0 there's no need to split the DP step, because it also needs to checkout the repo including LFS files for publication, that's why I put it together with the pages action so it's done in one flow.

**Comment by walkerlj0** [comment]
@makew0rld we still want to use Dpress to publish to IPFS & Agregoe

**Comment by walkerlj0** [comment]
@fauno can you either make a PR or type in a comment _exactly_ what should be in the github action workflow file?

**Comment by fauno** [comment]
> @fauno can you either make a PR or type in a comment _exactly_ what should be in the github action workflow file?

the way it's configured on the main branch it's ok and working, not sure why it's changed on this pr, but reverting that change should be ok to merge

**Pull request closed without merging**
